version: "3.8"

services:
  orderbook-fe:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POLKADEX_CHAIN=${POLKADEX_CHAIN}
        - GOOGLE_ANALYTICS=${GOOGLE_ANALYTICS}
        - API_REGION=${API_REGION}
        - GRAPHQL_URL=${GRAPHQL_URL}
        - IDENTITY_POOL_ID=${IDENTITY_POOL_ID}
        - USER_POOL_ID=${USER_POOL_ID}
        - USER_WEB_CLIENT_ID=${USER_WEB_CLIENT_ID}
        - LANDING_PAGE=${LANDING_PAGE}
        - SIGNUP_DISABLED=${SIGNUP_DISABLED}
        - PIN_POINT_CLIENT_ID=${PIN_POINT_CLIENT_ID}
        - MAINTENACE_MODE=${MAINTENACE_MODE}
        - SHOW_SHUTDOWN_POPUP=${SHOW_SHUTDOWN_POPUP}
        - UNDER_MAINTENACE=${UNDER_MAINTENACE}
        - ENABLE_LMP=${ENABLE_LMP}
        - IS_BRIDGE_ENABLED=${IS_BRIDGE_ENABLED}
        - MAIN_URL=${MAIN_URL}
        - BLOCKED_ASSETS=${BLOCKED_ASSETS}
        - DEFAULT_TRANSFER_TOKEN=${DEFAULT_TRANSFER_TOKEN}
        - SUBSCAN_API=${SUBSCAN_API}
        - SENTRY_DSN=${SENTRY_DSN}
        - SENTRY_AUTH=${SENTRY_AUTH}
        - DISABLED_FEATURES=${DISABLED_FEATURES}
        - GOOGLE_API_KEY=${GOOGLE_API_KEY}
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GRAPHQL_WS_URL=${GRAPHQL_WS_URL}
        - USE_NEW_BACKEND=${USE_NEW_BACKEND}
        - SUBQUERY_URL=${SUBQUERY_URL}
        - READ_ONLY_TOKEN=${READ_ONLY_TOKEN}
        - DEFAULT_THEA_SOURCE_CHAIN=${DEFAULT_THEA_SOURCE_CHAIN}
        - DEFAULT_THEA_DESTINATION_CHAIN=${DEFAULT_THEA_DESTINATION_CHAIN}
        - DISABLED_THEA_CHAINS=${DISABLED_THEA_CHAINS}
        - NEXT_PUBLIC_HYPERBRIDGE_URL=${NEXT_PUBLIC_HYPERBRIDGE_URL}
    env_file:
      - .env
    # You can set ECR_REGISTRY in your .env file
    # Example: ECR_REGISTRY=123456789012.dkr.ecr.us-east-1.amazonaws.com
    image: 907213364062.dkr.ecr.ap-south-1.amazonaws.com/polkadex-orderbook-fe:latest
    container_name: polkadex-orderbook-fe
    ports:
      - "8000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
