/* eslint-disable */
// Originally generated by AWS Amplify, now hand-maintained: the endpoints come
// from the environment rather than being baked in, so it is no longer
// regenerated and IS safe to edit.

// Amplify builds the subscription URL by appending "/realtime" to the GraphQL
// endpoint, so a trailing slash in GRAPHQL_URL produces
// "wss://host//realtime" - two slashes - and the WebSocket handshake fails
// while plain HTTP queries keep working, because servers tolerate "//" in a
// path but AppSync's realtime route does not match.
//
// That failure is invisible in the wrong place: subscriptions die (no live
// orderbook or candle updates) while every query succeeds, so it reads as a
// backend outage. Normalising here rather than relying on every .env across
// every deployment getting it right.
const stripTrailingSlash = (url) => (url || "").replace(/\/+$/, "");

const awsmobile = {
    "aws_project_region": process.env.API_REGION,
    "aws_appsync_graphqlEndpoint": stripTrailingSlash(process.env.GRAPHQL_URL),
    "aws_appsync_region": process.env.API_REGION,
    "aws_appsync_authenticationType": "AWS_LAMBDA",
    ssr: true,
  };


export default awsmobile;
